watch and jk hack

diff --git a/aliases b/aliases
--- a/aliases
+++ b/aliases
@@ -742,7 +742,7 @@ zz () {
     fi
 }
 
-watchexec() {
+watch() {
     if [ -z "$1" ]; then
         tldr watchexec
         return
@@ -750,7 +750,13 @@ watchexec() {
     if $(pwd -P | grep -q "^\/mnt\/c\/*"); then
         cmd /c watchexec "$@"
     else
-        watchexec "$@"
+        if ! command -v watchexec &> /dev/null
+        then
+            echo "watchexec could not be found"
+            echo "install with 'wget https://github.com/watchexec/watchexec/releases/download/cli-v1.19.0/watchexec-1.19.0-x86_64-unknown-linux-musl.deb && sudo dpkg -i watchexec-1.19.0-x86_64-unknown-linux-gnu.deb'"
+        else
+            watchexec "$@"
+        fi
     fi
 }
 pywatch() {
@@ -758,11 +764,7 @@ pywatch() {
         echo "first arg must be python file followed by optional args"
         return
     fi
-    if $(pwd -P | grep -q "^\/mnt\/c\/*"); then
-        cmd /c watchexec -c -- python "$@"
-    else
-        watchexec  -c -- python "$@"
-    fi
+    watch  -c -- python "$@"
 }
 
 # apt install trash-cli. trash ends up in ~/.local/share/Trash/. use trash-list to list. trash-restore to restore.
